### ISSUE TITLE
An exception occurred while running on the Mac platform

### ISSUE THREAD

**Issue by Vito258** [microspaze/FFImageLoading.Maui#1]
### Description

"Could not resolve type with token 01000005 from typeref (expected class 'System.Runtime.CompilerServices.InternalsVisibleToAttribute' in assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')"
### Steps to Reproduce

In the AppDelegate.cs file, when I run the FinishedLaunching method, var ret = base.FinishedLaunching(app, options); An exception has occurred in this code

### Basic Information

- Version with issue: Current version
- Last known good version: 
- Platform: Mac/iOS

**Comment by Vito258** [comment]
![4c16c1a68d0ecf2e0a6365907750acc3](https://github.com/microspaze/FFImageLoading.Maui/assets/103879360/a2e0fa5d-96a3-4f4e-8a8b-18c14a6695b9)

**Comment by microspaze** [comment]
> ![4c16c1a68d0ecf2e0a6365907750acc3](https://user-images.githubusercontent.com/103879360/267888437-a2e0fa5d-96a3-4f4e-8a8b-18c14a6695b9.png)

Can you delete bin & obj folders and rebuild the solution again? 

OR

You can use Jetbrains Rider to build the app, it's more efficient.

**Comment by Vito258** [comment]
hi@microspaze
I had tried deleting bin & obj folders and rebuilding the solution again,But it didn't work.I had made a demo to try,  when I added the nuget package and tried to use it,still reporting this exception

**Comment by Vito258** [comment]
> > ![4c16c1a68d0ecf2e0a6365907750acc3](https://user-images.githubusercontent.com/103879360/267888437-a2e0fa5d-96a3-4f4e-8a8b-18c14a6695b9.png)
> 
> 是否可以删除 bin 和 obj 文件夹并再次重建解决方案？
> 
> 或
> 
> 您可以使用 Jetbrains Rider 来构建应用程序，它更有效率。

hi@microspaze
I had tried deleting bin & obj folders and rebuilding the solution again,But it didn't work.I had made a demo to try,  when I added the nuget package and tried to use it,still reporting this exception

**Comment by microspaze** [comment]
@Vito258 Can you download the FFImageLoading.Maui source code and rund the samples/Sample to check whether if it works?

**Comment by microspaze** [comment]
I use Xcode 14.3.1 and it works. Maybe you can give a little demo pack then I can have a look to find the real cause. And I strongly suggest you to try Jetbrains/Rider as maui development IDE on macos, VS for mac sometimes has some strange bug.
[Jetbrains/Rider](https://www.jetbrains.com/rider/)

**Comment by Vito258** [comment]
@microspaze Hello, I have recently encountered a new issue. Could please explain why GIFs tend to pause after a certain period of time instead of smoothly playing through the entire cycle? Is there an effective solution available?

**Comment by microspaze** [comment]
@Vito258  The GIF sample in FFImageLoading.Maui works fine. You can give your GIF file, then we can test it to check the real cause.

**Comment by Vito258** [comment]
@microspaze 
![walkthrough-03](https://github.com/microspaze/FFImageLoading.Maui/assets/103879360/87881227-00b6-4d41-a5e2-47d39b48e954)
This is my gif

**Comment by microspaze** [comment]
@Vito258  This gif works fine for me in both iOS simulator and device. I use this gif to run the sample for 5 minutes and it has not been paused. Can you give more detail about your issue? Is it a always reproduced bug or incidental issue? You can give a  screen recording video and tell me what device or simulator you use.

**Comment by Vito258** [comment]
@microspaze I used the Android emulator provided by VsStudio,  and this video recording shows that GIFs seem to need buffering before they play smoothly.
[untitled.webm](https://github.com/microspaze/FFImageLoading.Maui/assets/103879360/6053efea-4aa3-4d97-9ce9-d6e82527ce38)

**Comment by Vito258** [comment]
@microspaze Hello, do you have any insights?  It appears to be an issue with this gif,  I have tried using other GIFs and it can play smoothly,

**Comment by microspaze** [comment]
@Vito258 I will check it for Android Simulator and device. Can you also run your app to a real android device to reproduce this issue?

**Comment by Vito258** [comment]
@microspaze Yes, real android device has this issue. And I had tried any other FFImageLoading nuget it happened too. I think it maybe FFImageLoading's issue.

**Comment by microspaze** [comment]
@Vito258 I had tested your gif on my computer. I found that your gif has 19 pictures and last 2 pictures are same. So I deleted the last picture and reduce the play duration of each picture. You can try the modified gif file by your own.

CurryShop-18-0.1s/picture
![CurryShop-0 1spp](https://github.com/microspaze/FFImageLoading.Maui/assets/17372096/46737b80-9771-448a-bee2-4bbb8e1f8c09)

CurryShop-18-0.2s/picture
![CurryShop-0 2spp](https://github.com/microspaze/FFImageLoading.Maui/assets/17372096/36d5394f-0856-4418-828a-fd14213cd51a)

CurryShop-19-0.1s/picture (The original gif but speed up)
![CurryShop-19-0 1spp](https://github.com/microspaze/FFImageLoading.Maui/assets/17372096/7f263c96-cad1-48c9-a207-ac3a23a349a0)

**Comment by Vito258** [comment]
@microspaze Ohhhh,thanks.These GIFs play normally
