### ISSUE TITLE
AspectFill not working on Android for CachedImage control

### ISSUE THREAD

**Issue by brendan-holly-modea** [microspaze/FFImageLoading.Maui#13]
### Description

Setting `Aspect="AspectFill"` on Android for `CachedImage` controls does not work as expected if the image aspect ratio is significantly different than the aspect ratio of the container (e.g. a rectangular image in a square container). `AspectFill` is working normally on iOS and works on both platforms with the Maui `Image` control.

### Steps to Reproduce

1. Create a container like a `Grid` and add a `ffimageloading:CachedImage` control with a `HeightRequest` and `WidthRequest`.
2. Set the `Aspect` of this image to `AspectFill` so that the image should clip itself to fill the container without modifying the aspect ratio of the image.
3. Verify that the image is stretching past the bounds of the container.

See code and sample app below.

### Expected Behavior

The `CachedImage` should fill the boundaries using `AspectFill` on Android just like the MAUI `Image` control and the iOS `CachedImage` control does

### Actual Behavior

Using `Aspect="AspectFill"` on Android results in the image ignoring the boundaries of the container and stretching beyond those boundaries. As stated above, this does not happen on iOS or using the Maui Image control.

### Basic Information

- Version with issue: 1.0.6 on .net7
- Last known good version: Unknown
- Platform: Android

### Screenshots

This screenshot details the behavior on both platforms. Android is on the left and iOS is on the right:

<img width="834" alt="Screenshot 2024-02-02 at 11 40 05 AM" src="https://github.com/microspaze/FFImageLoading.Maui/assets/88406334/4e3902ce-ff83-4580-ab76-e4353f9e9780">

#### Code to compare CachedImage with MAUI Image

```
 <Grid ColumnDefinitions="130" RowDefinitions="130, 130">
    <ffimageloading:CachedImage Source="maui_beach_wikimedia.png" HeightRequest="130" WidthRequest="130"
          Aspect="AspectFill" IsVisible="true"
           AutomationProperties.IsInAccessibleTree="False">
    </ffimageloading:CachedImage>
    <Image Source="maui_beach_wikimedia.png" HeightRequest="130" WidthRequest="130" Grid.Row="1"
          Aspect="AspectFill" IsVisible="true"AutomationProperties.IsInAccessibleTree="False">
    </Image>
</Grid>
```

#### Sample app reproduction

https://github.com/brendan-holly-modea/cache-image-issue

Check out `MainPage.xaml` by running the app with MAUI on .net7 on Android and iOS to see the issue.

**Comment by microspaze** [comment]
Fixed by https://github.com/microspaze/FFImageLoading.Maui/commit/35f49b3513f2af28ad96f0dcb7f968ff965f587f

I will published a new version of lib later after testing all merged fixes.

**Thanks very much for this issue reporting!**

**Comment by brendan-holly-modea** [comment]
I dug into the [MAUI source code](https://github.com/dotnet/maui/blob/main/src/Core/src/Handlers/Image/ImageHandler.Android.cs), and it looks like this may be their way of handling clipping the image when `AspectFill` is selected. (See the overriding method `PlatformArrange`)

```
if (PlatformView.GetScaleType() == ImageView.ScaleType.CenterCrop)
{
    // If the image is center cropped (AspectFill), then the size of the image likely exceeds
    // the view size in some dimension. So we need to clip to the view's bounds.

    var (left, top, right, bottom) = PlatformView.Context!.ToPixels(frame);
    var clipRect = new Android.Graphics.Rect(0, 0, right - left, bottom - top);
    PlatformView.ClipBounds = clipRect;
}
```

**Comment by brendan-holly-modea** [comment]
@microspaze I [opened a PR](https://github.com/microspaze/FFImageLoading.Maui/pull/14) which appears to fix these issues for me locally.

**Comment by microspaze** [comment]
Merged and refined. https://www.nuget.org/packages/FFImageLoading.Maui/1.0.8

**Comment by brendan-holly-modea** [comment]
@microspaze This is working great for me. Thank you!
