### ISSUE TITLE
Potential race condition during loading of image source and LoadingPlaceholder

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [microspaze/FFImageLoading.Maui#24]
### Description

When LoadingPlaceholder is specified, and the requested image source URL is very fast (e.g. small image from localhost), then it seems like a race condition during loading of both images. 

The final displayed image is the LoadingPlaceholder instead of the source.

If LoadingPlaceholder is removed, then all works fine.
If Source is large image of slow responding URL, then all works fine.

### Steps to Reproduce

Image control setup

```
<?xml version="1.0" encoding="UTF-8"?>
<ffimage:CachedImage 
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui" 
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:d="http://xamarin.com/schemas/2014/forms/design"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:ffimage="clr-namespace:FFImageLoading.Maui;assembly=FFImageLoading.Maui"
    mc:Ignorable="d"
    x:Class="MAUITest.FFImageWrapper"
    x:Name="image" 
    Aspect="AspectFit" 
    CacheDuration="30" 
    CacheType="Disk" 
    LoadingPlaceholder="loading.gif" 
    ErrorPlaceholder="error.png"
    HorizontalOptions="FillAndExpand"
    DownsampleToViewSize="True"
    >
</ffimage:CachedImage>
```

### Expected Behavior

Image should appear

### Actual Behavior

Image stuck on LoadingPlaceholder

### Basic Information

- Version with issue: 1.1.3
- Last known good version: 1.1.0
- Platform: Android

**Comment by microspaze** [comment]
@EvgenyMuryshkin  Is this issue very easy to reproduce? I tested a lot of test case but still can not reproduce this problem. Can you upload a little demo project?

**Comment by EvgenyMuryshkin** [comment]
> @EvgenyMuryshkin Is this issue very easy to reproduce? I tested a lot of test case but still can not reproduce this problem. Can you upload a little demo project?

Hi, as usual, the clean project works with no problems. I will try to distill what exactly is wrong.
What I noticed, is that my loading.gif is the animated spinner and it does not spin in the prod app setup, where issue with loading.
But it spins in the clean project.

There is complex controls hierarchy, with third-party control in the middle. Will try to track it into clean repo.

**Comment by EvgenyMuryshkin** [comment]
@microspaze please have a look at this sample repo.
https://github.com/EvgenyMuryshkin/FFImageTest/tree/main

**Comment by EvgenyMuryshkin** [comment]
@microspaze added a background task to simulate the app's hard work, the issue is easily reproducible now, every 5th load or so.

**Comment by EvgenyMuryshkin** [comment]
@microspaze, also, we have the same issue with Xamarin.FFImageLoading.Forms.
Stayed on 2.4.9.961 because the newer version behaves the same, but for Xamarin it did not matter because of the upcoming migration to MAUI.

**Comment by microspaze** [comment]
Fixed in the latest version 1.1.6 https://www.nuget.org/packages/FFImageLoading.Maui/1.1.6

Thanks for reporting!

This problem can be only reproduced when using a gif image as placeholder. The root cause is on Android platform the GIF feature is impletemented by FFAnimatedDrawable which is based by BitmapDrawable.  The FFAnimatedDrawable initialization takes the first bitmap of AnimatedImages as the base bitmap. **So it may not be disposed and can not be replaced.**

```
public class FFAnimatedDrawable : SelfDisposingBitmapDrawable, ISelfDisposingAnimatedBitmapDrawable
{
	......
	internal FFAnimatedDrawable(Resources resources, Bitmap bitmap, IAnimatedImage<Bitmap>[] animatedImages) 
             :  base(resources, bitmap)
	{
		AnimatedImages = animatedImages;
	}

	public IAnimatedImage<Bitmap>[] AnimatedImages { get; private set; }
}
```

The fix is to clear both AnimatedImages and the shadow bitmap when replace imageView content. https://github.com/microspaze/FFImageLoading.Maui/commit/44b5439d4c882cf65376cfb279df62d42d3cb995

@EvgenyMuryshkin please help to verify the fix on the lib version 1.1.6 when you are free.

**Comment by EvgenyMuryshkin** [comment]
@microspaze seems to be working fine, thanks. Great work!

**Comment by EvgenyMuryshkin** [comment]
@microspaze 1.2.0 works ok for my scenario, thanks.
