### ISSUE TITLE
InvalidateCacheEntryAsync gives a null pointer exception

### ISSUE THREAD

**Issue by apoorvadixit-ttc** [microspaze/FFImageLoading.Maui#27]
### Description

When a cached image content has changed, we invalidate the cache. This used to work in Xamarin like this:
`await ImageService.Instance.InvalidateCacheEntryAsync(PicturePath, FFImageLoading.Cache.CacheType.All, true);`

### Steps to Reproduce

Try to invalidate the cache by force like this:
`await ImageService.Instance.InvalidateCacheEntryAsync(PicturePath, FFImageLoading.Cache.CacheType.All, true);`

### Expected Behavior

This should delete the cache.

### Actual Behavior

Throws an exception: System.NullReferenceException: 'Object reference not set to an instance of an object.'

### Basic Information

- Version with issue: 1.1.9
- Last known good version:
- Platform: MAUI/Android

**Comment by microspaze** [comment]
Fixed in version 1.2.0. https://www.nuget.org/packages/FFImageLoading.Maui/1.2.0

Thanks for reporting this issue. Please help to verify the fixing on the latest nuget version when you are free.

**Comment by apoorvadixit-ttc** [comment]
> Fixed in version 1.2.0. https://www.nuget.org/packages/FFImageLoading.Maui/1.2.0
> 
> Thanks for reporting this issue. Please help to verify the fixing on the latest nuget version when you are free.

Can confirm that this is now fixed. Brilliant work, thank you so much for quick fixes (and the migration to MAUI)!
