### ISSUE TITLE
Not able to access ImageService class in FFImageLoading.Maui 1.2.0

### ISSUE THREAD

**Issue by bharataghera90** [microspaze/FFImageLoading.Maui#28]
### Description

Hello, 

Hope you are doing well. I wan to use this library in my .net ios project. So I have installed the nuget FFImageLoading.Maui 1.2.0
and try to use it. But I am not able to access ImageService class.

In the project, I have used it like
`using FFImageLoading;`
` ImageService.Instance.LoadFile(fileName).IntoAsync(imageView)`

It says "The name 'ImageService' does not exist in the current context".
However, I have imported FFImageLoading.

I have cloned this project & created the nuget with it by removing [Preserve(AllMembers = true)] from ImageService class in 
"source/FFImageLoading.Maui/Platforms/iOS/Foundations/ImageService.cs". If I use my package, I can use ImageService class.

Please guide me if the class is not intended to use.
Thanks for all your hard work to manage this library.

### Steps to Reproduce

1. Install nuget FFImageLoading.Maui 1.2.0.
2. Use it in the .net ios project like `ImageService.Instance.LoadFile(fileName).IntoAsync(imageView)`

### Expected Behavior

"The name 'ImageService' does not exist in the current context".

### Actual Behavior

It should allow to use in .net ios project.

### Basic Information

- Version with issue: Nuget FFImageLoading.Maui 1.2.0
- Last known good version: 
- Platform: 

### Screenshots

N/A

### Reproduction Link / Code

N/A

**Comment by microspaze** [comment]
What kind of iOS project does you use FFImageLoading.Maui lib, pure .NET iOS project or Maui iOS project? Can you provide a little demo project for this issue?

**Comment by bharataghera90** [comment]
[IosTest.zip](https://github.com/microspaze/FFImageLoading.Maui/files/15007568/IosTest.zip)
Hi microspaze, I have attached the sample project with it. Please check it when you get some time.
Thanks for the quick reply.

**Comment by microspaze** [comment]
@bharataghera90  I don't think you can use FFImageLoading.Maui in the PURE .NET iOS project like IosTest.zip. FFImageLoading.Maui lib contains a lot of MAUI related methods and logic. You can create a MAUI project and use FFImageLoading.Maui in the iOS platform code under the **Project/Platforms/iOS** folder.

**FFImageLoading.Maui CAN BE USED ONLY IN MAUI PROJECTS.**

I'm sorry for that.

**Comment by bharataghera90** [comment]
Thanks @microspaze for the quick reply. That's ok.

**Comment by bharataghera90** [comment]
Hi @microspaze. By mistake, I have raised the pull request & close it.
https://github.com/microspaze/FFImageLoading.Maui/pull/30.

Please revert the changes if it has been affected to your repository. Apologise once again.
