### ISSUE TITLE
Android Release build crash on startup after upgrade 1.1.9 to 1.2.0

### ISSUE THREAD

**Issue by EvgenyMuryshkin** [microspaze/FFImageLoading.Maui#34]
Hi,

After upgrading from 1.1.9 to 1.2.0, the release build crashes on startup with the next error, reported in the Device Log.

```
* Assertion at /_w/1/s/src/mono/mono/mini/aot-runtime.c:3810, condition ‘is_ok (error)' not met, function:decode_patch, module ‘Test.MAUI.dIl.so’ is unusable (GUID of dependent assembly FFimageLoading.Maui doesn't match (expected '9753E4DA-4D73-4EED-9672-A1E4F942229A', got '182F2520-718C-4D1B-BBCF-84A5E0C25802')).
```

GUIDs seem to be regenerating from build to build.

Android API 34
MAUI 8.0.14 - 8.0.21

**Comment by microspaze** [comment]
Can you provide a demo project? It seems like a AOT build related issue. Maybe change some project setting can fix it.

**Comment by EvgenyMuryshkin** [comment]
Hi,

Please have a look here, nothing specific is configured for AOT.

https://github.com/EvgenyMuryshkin/FFImageTest/tree/main

1.1.9 in release configuration runs ok, with 1.2.0 it does not.

I will report this to Microsoft as well, other libraries also do the same thing.

Thanks,
Regards,
Evgeny

**Comment by microspaze** [comment]
JUST DELETE **FFImageTest\obj** FIX IT. You can try it by yourself.

**Comment by EvgenyMuryshkin** [comment]
OMG, not again :(
How much time has been wasted over the last 25 years because Visual Studio can't properly clean the project? 

Thanks.
