### ISSUE TITLE
Android app crashes when using using multiple CachedImage for showing multiple gifs

### ISSUE THREAD

**Issue by Th3L0x** [microspaze/FFImageLoading.Maui#35]
### Description

Trying to create a control that holds gif images (url source), the app crashes when I start scrolling in the collectionview. 
According to the log, the problem occurs while loading the gif.

### Steps to Reproduce

Put mutliple gifs (25-30) CachedImage CacheType="None" in a collectionview

### Basic Information

- Version with issue: 1.2.3
- Platform:  Android

Log:

**System.AggregateException:** 'One or more errors occurred. (Unbalanced enter/exit)'

monodroid-assembly] Shared library 'liblog' not loaded, p/invoke '__android_log_print' may fail
[monodroid-net] Exception caught while cancelling connection: Java.IO.IOException: Canceled
[monodroid-net]    at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20370
[monodroid-net]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeAbstractVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 47
[monodroid-net]    at Javax.Net.Ssl.HttpsURLConnectionInvoker.Connect() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Javax.Net.Ssl.HttpsURLConnection.cs:line 443
[monodroid-net]    at Xamarin.Android.Net.AndroidMessageHandler.<>c__DisplayClass133_0.<ConnectAsync>b__0() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Xamarin.Android.Net/AndroidMessageHandler.cs:line 526
[monodroid-net]   --- End of managed Java.IO.IOException stack trace ---
[monodroid-net] java.io.IOException: Canceled
[monodroid-net] 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:183)
[monodroid-net] 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[monodroid-net] 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[monodroid-net] 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[monodroid-net] 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[monodroid-net] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[monodroid-net] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[monodroid-net] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
[monodroid-net] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
[monodroid-net] 
[monodroid-net]   --- End of managed Java.IO.IOException stack trace ---
[monodroid-net] java.io.IOException: Canceled
[monodroid-net] 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:183)
[monodroid-net] 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[monodroid-net] 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[monodroid-net] 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[monodroid-net] 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[monodroid-net] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[monodroid-net] 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[monodroid-net] 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
[monodroid-net] 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
[monodroid-net] 
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. (Unbalanced enter/exit)
[mono-rt]  ---> Java.Lang.IllegalStateException: Unbalanced enter/exit
[mono-rt]    at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 20370
[mono-rt]    at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 66
[mono-rt]    at Java.IO.InputStream.Close() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net8.0/android-34/mcw/Java.IO.InputStream.cs:line 116
[mono-rt]    at Android.Runtime.InputStreamInvoker.Close() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/InputStreamInvoker.cs:line 62
[mono-rt]    at System.IO.Stream.Dispose()
[mono-rt]    at System.IO.BufferedStream.Dispose(Boolean disposing)
[mono-rt]    at System.IO.Stream.Close()
[mono-rt]    at System.IO.Stream.Dispose()
[mono-rt]    at System.IO.DelegatingStream.Dispose(Boolean disposing)
[mono-rt]    at System.IO.Stream.Close()
[mono-rt]    at System.IO.Stream.Dispose()
[mono-rt]    at FFImageLoading.ObjectExtensions.TryDispose(IDisposable obj)
[mono-rt]    at FFImageLoading.Cache.DownloadCache.<>c__DisplayClass23_1.<DownloadAsync>b__1()
[mono-rt]    at System.Threading.CancellationToken.<>c.<Register>b__12_0(Object obj)
[mono-rt]    at System.Threading.CancellationTokenSource.Invoke(Delegate d, Object state, CancellationTokenSource source)
[mono-rt]    at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
[mono-rt]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[mono-rt] --- End of stack trace from previous location ---
[mono-rt]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[mono-rt]    at System.Threading.CancellationTokenSource.CallbackNode.ExecuteCallback()
[mono-rt]    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
[mono-rt]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[mono-rt] java.lang.IllegalStateException: Unbalanced enter/exit
[mono-rt] 	at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:64)
[mono-rt] 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
[mono-rt] 	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
[mono-rt] 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
[mono-rt] 	at com.android.okhttp.internal.Util.skipAll(Util.java:165)
[mono-rt] 	at com.android.okhttp.internal.Util.discard(Util.java:147)
[mono-rt] 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:412)
[mono-rt] 	at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:397)
[mono-rt] 	at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:385)
[mono-rt] 
[mono-rt]   --- End of managed Java.Lang.IllegalStateException stack trace ---
[mono-rt] java.lang.IllegalStateException: Unbalanced enter/exit
[mono-rt] 	at com.android.okhttp.okio.AsyncTimeout.enter(AsyncTimeout.java:64)
[mono-rt] 	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
[mono-rt] 	at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:51)
[mono-rt] 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:395)
[mono-rt] 	at com.android.okhttp.internal.Util.skipAll(Util.java:165)
[mono-rt] 	at com.android.okhttp.internal.Util.discard(Util.java:147)
[mono-rt] 	at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:412)
[mono-rt] 	at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:397)
[mono-rt] 	at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:385)
[mono-rt] 
[mono-rt]    --- End of inner exception stack trace ---
[mono-rt]    at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
[mono-rt]    at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
[mono-rt]    at System.Threading.CancellationTokenSource.TimerCallback(Object state)
[mono-rt]    at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
[mono-rt]    at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
[mono-rt]    at System.Threading.TimerQueue.FireNextTimers()
[mono-rt]    at System.Threading.TimerQueue.System.Threading.IThreadPoolWorkItem.Execute()
[mono-rt]    at System.Threading.ThreadPoolWorkQueue.Dispatch()
[mono-rt]    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
[mono-rt]    at System.Threading.Thread.StartCallback()
[Maui.Test] Background concurrent copying GC freed 5450(4673KB) AllocSpace objects, 12(9752KB) LOS objects, 49% free, 21MB/43MB, paused 130us,72us total 569.124ms
[BpBinder] onLastStrongRef automatically unlinking death recipients: <uncached descriptor>

**Comment by microspaze** [comment]
It seems a concurrent web loading exception. Can you upload a demo project? It will help me save a lot of time to prepare the debug project.

**Comment by Th3L0x** [comment]
Unfortunately, I can't share the code, but I will try to make the sample app

**Comment by microspaze** [comment]
Fixed in the latest version 1.2.4 https://www.nuget.org/packages/FFImageLoading.Maui/1.2.4

Please help to verify the fix when you are free. Thanks.

**Comment by Th3L0x** [comment]
Thanks, it's working now!
