### ISSUE TITLE
There seems to be a problem when distributing the 1.2.5 release.

### ISSUE THREAD

**Issue by YoonYoeungJun** [microspaze/FFImageLoading.Maui#37]
### Description

I used 1.2.4 and updated to 1.2.5 today. It runs in debug mode and there is no problem, but when deployed, the app fails to start.

## App class OnStart
```
 protected override void OnStart() {
     base.OnStart();

     InitializeFFImageLoading();
 }
```

## FFImageLoading initialize
```
private static readonly HttpClient httpClient = new HttpClient(new HttpClientHandler {
    MaxConnectionsPerServer = 10 // 병렬 연결 수 제한
}) {
    Timeout = TimeSpan.FromSeconds(15) // 타임아웃 설정
};
private void InitializeFFImageLoading() {
    // FFImageLoading 설정
    ImageService.Instance.Initialize(new FFImageLoading.Config.Configuration {
        HttpClient = httpClient,
        MaxMemoryCacheSize = 300 * 1024 * 1024, // 50 MB
        TransformPlaceholders = true,
        DownsampleInterpolationMode = FFImageLoading.Work.InterpolationMode.Default,
        BitmapOptimizations = true,
        ClearMemoryCacheOnOutOfMemory = true,
        SchedulerMaxParallelTasks = 4,
        FadeAnimationEnabled = true,
        FadeAnimationForCachedImages = false,
        ExecuteCallbacksOnUIThread = true,
        InvalidateLayout = true,
        VerboseLogging = false
    });
    // 캐시 초기화 (옵션)
    //ImageService.Instance.InvalidateCacheAsync(CacheType.All);
}
```

### Steps to Reproduce

If you downgrade the problematic 1.2.5 to 1.2.4 and deploy it, there will be no problem running it. If you update it again to 1.2.5, the app will terminate as soon as it runs.

### Expected Behavior

When I run the app, it immediately stops working.

This is only true in release mode

### Actual Behavior

If you downgrade to 1.2.4 and deploy it in release mode, it will work normally

### Basic Information

- Version with issue: 1.2.5
- Last known good version: 1.2.4
- Platform: Android

**Comment by microspaze** [comment]
Can you try to delete **obj folder** AND **REBUILD** ? It may be a VS bug for cleaning. Just like issue #34 (Android Release build crash on startup after upgrade 1.1.9 to 1.2.0)

**Comment by YoonYoeungJun** [comment]
thank you
Removing the obj folder solved my error.

When I published the app after removing the obj folder, all the icons using FontImageSource appeared broken. I upgraded the version again, rebuilt it, and created a new version, and it displayed normally. I tested it twice, and both times after removing the obj folder, it appeared twice. I had to go through a release, can you give me some advice on this?

**Comment by microspaze** [comment]
It's not need to remove the obj folder everytime when you build a release. You just need do it when you upgrade the third-party lib's version. It's a a little tricky experience when you are developing with Visual Studio.
