### ISSUE TITLE
Crash when trying to use `SvgImageSource.FromResource` as `ToolbarItem.IconImageSource`

### ISSUE THREAD

**Issue by sovdchains** [microspaze/FFImageLoading.Maui#42]
### Description

When using `SvgImageSource.FromResource` to use the image as e.g. `ToolbarItem.IconImageSource` the following exception occurs:

 ```
 Unhandled Exception:
System.InvalidOperationException: Unable to find the image source type because none of the interfaces on SvgImageSource were derived from IImageSource.
   at Microsoft.Maui.Hosting.ImageSourceServiceProvider.CreateImageSourceTypeCacheEntry(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2[[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Type, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].GetOrAdd(Type key, Func`2 valueFactory)
   at Microsoft.Maui.Hosting.ImageSourceServiceProvider.GetImageSourceType(Type imageSource)
  …
 ```

Am I missing something?

### Steps to Reproduce

- Use Sample app
- Add this property to `SvgSamplePageModel`:

```csharp
 public ImageSource ToolbarIcon => SvgImageSource.FromResource("Sample.sample.svg", typeof(SvgSamplePageModel));
 ```
 
 - Add this toolbar item to `SvgSamplePage`
 
 ```xaml
   <ContentPage.ToolbarItems>
      <ToolbarItem IconImageSource="{Binding ToolbarIcon}"/>
  </ContentPage.ToolbarItems>
 ```

### Expected Behavior

Seeing the SVG as a toolbar item icon

### Actual Behavior

Crash

### Basic Information

- Version with issue: 1.2.6
- Last known good version: n/a
- Platform: ios (probably all?)

### Screenshots

n/a

### Reproduction Link / Code

see above

**Comment by microspaze** [comment]
**I'm sorry but you can not use SvgImageSource like this.** SvgImageSource.FromResource can returns a valid ImageSource model, but it does not impletment the MAUI IImageSource interface which means **the SvgImageSource can not be used as image source for MAUI system's image source** but only valid for **SvgCachedImage** or **CachedImage with SvgImageSourceConverter**.

**Comment by sovdchains** [comment]
@microspaze
Thats really unfortunate, but thanks anyway!
