### ISSUE TITLE
Where is ImageService.Instance?

### ISSUE THREAD

**Issue by Inrego** [microspaze/FFImageLoading.Maui#8]
### Description

I'm missing `ImageService.Instance`, so I can configure the HttpClient.

**Comment by Inrego** [comment]
NVM I found it through dependency service injection.

**Comment by sawankumarbundelkhandi** [comment]
got it. Thanks

#if IOS || MACCATALYST
			services.AddSingleton<IImageService<UIKit.UIImage>, ImageService>();
#elif ANDROID
			services.AddSingleton<IImageService<FFImageLoading.Drawables.SelfDisposingBitmapDrawable>, ImageService>();
#elif WINDOWS
			services.AddSingleton<IImageService<Microsoft.UI.Xaml.Media.Imaging.BitmapSource>, ImageService>();
#endif

**Comment by Inrego** [comment]
The service is registered automatically when you use the `.UseFFImageLoading()` method in you app startup.
When you need it, you request the following type: `IImageService<TImageContainer>`
For example in ViewModel constructor or in other ways.

**Comment by sawankumarbundelkhandi** [comment]
Like this in viewmodel constructor then?

#if IOS
        private readonly IImageService<UIKit.UIImage> _imageService;
#elif ANDROID
        private readonly IImageService<FFImageLoading.Drawables.SelfDisposingBitmapDrawable> _imageService;
#endif

#if IOS
        public CacheService(IBlobCache blobCache, IImageService<UIKit.UIImage> imageService)
#elif ANDROID
        public CacheService(IBlobCache blobCache, IImageService<FFImageLoading.Drawables.SelfDisposingBitmapDrawable> imageService)
#endif
        {
            _blobCache = blobCache;
            _imageService = imageService;
        }

**Comment by Inrego** [comment]
No, like this:

```
private readonly IImageService<TImageContainer> _imageService;
public CacheService(IBlobCache blobcache, IImageService<TImageContainer> imageService)
{
    _blobCache = blobCache;
    _imageService = imageService
}
```

**Comment by sawankumarbundelkhandi** [comment]
Thanks, got it working by adding this GlobalUsings into the code. https://github.com/microspaze/FFImageLoading.Maui/blob/main/samples/Sample/GlobalUsings.cs

**Comment by Inrego** [comment]
Ah yes, I missed that part.
